/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoshqaruvRouteImport } from './routes/boshqaruv'
import { Route as KassaRouteImport } from './routes/kassa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MijozlarRouteImport } from './routes/mijozlar'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SozlamalarRouteImport } from './routes/sozlamalar'
import { Route as TovarlarRouteImport } from './routes/tovarlar'
import { Route as UmumiyRouteImport } from './routes/umumiy'
import { Route as VerifyCodeRouteImport } from './routes/verify-code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoshqaruvRoute = BoshqaruvRouteImport.update({
  id: '/boshqaruv',
  path: '/boshqaruv',
  getParentRoute: () => rootRouteImport,
} as any)
const KassaRoute = KassaRouteImport.update({
  id: '/kassa',
  path: '/kassa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MijozlarRoute = MijozlarRouteImport.update({
  id: '/mijozlar',
  path: '/mijozlar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlamalarRoute = SozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => rootRouteImport,
} as any)
const TovarlarRoute = TovarlarRouteImport.update({
  id: '/tovarlar',
  path: '/tovarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const UmumiyRoute = UmumiyRouteImport.update({
  id: '/umumiy',
  path: '/umumiy',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify-code',
  path: '/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boshqaruv': typeof BoshqaruvRoute
  '/kassa': typeof KassaRoute
  '/login': typeof LoginRoute
  '/mijozlar': typeof MijozlarRoute
  '/register': typeof RegisterRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/tovarlar': typeof TovarlarRoute
  '/umumiy': typeof UmumiyRoute
  '/verify-code': typeof VerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boshqaruv': typeof BoshqaruvRoute
  '/kassa': typeof KassaRoute
  '/login': typeof LoginRoute
  '/mijozlar': typeof MijozlarRoute
  '/register': typeof RegisterRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/tovarlar': typeof TovarlarRoute
  '/umumiy': typeof UmumiyRoute
  '/verify-code': typeof VerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boshqaruv': typeof BoshqaruvRoute
  '/kassa': typeof KassaRoute
  '/login': typeof LoginRoute
  '/mijozlar': typeof MijozlarRoute
  '/register': typeof RegisterRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/tovarlar': typeof TovarlarRoute
  '/umumiy': typeof UmumiyRoute
  '/verify-code': typeof VerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boshqaruv'
    | '/kassa'
    | '/login'
    | '/mijozlar'
    | '/register'
    | '/sozlamalar'
    | '/tovarlar'
    | '/umumiy'
    | '/verify-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boshqaruv'
    | '/kassa'
    | '/login'
    | '/mijozlar'
    | '/register'
    | '/sozlamalar'
    | '/tovarlar'
    | '/umumiy'
    | '/verify-code'
  id:
    | '__root__'
    | '/'
    | '/boshqaruv'
    | '/kassa'
    | '/login'
    | '/mijozlar'
    | '/register'
    | '/sozlamalar'
    | '/tovarlar'
    | '/umumiy'
    | '/verify-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoshqaruvRoute: typeof BoshqaruvRoute
  KassaRoute: typeof KassaRoute
  LoginRoute: typeof LoginRoute
  MijozlarRoute: typeof MijozlarRoute
  RegisterRoute: typeof RegisterRoute
  SozlamalarRoute: typeof SozlamalarRoute
  TovarlarRoute: typeof TovarlarRoute
  UmumiyRoute: typeof UmumiyRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boshqaruv': {
      id: '/boshqaruv'
      path: '/boshqaruv'
      fullPath: '/boshqaruv'
      preLoaderRoute: typeof BoshqaruvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kassa': {
      id: '/kassa'
      path: '/kassa'
      fullPath: '/kassa'
      preLoaderRoute: typeof KassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mijozlar': {
      id: '/mijozlar'
      path: '/mijozlar'
      fullPath: '/mijozlar'
      preLoaderRoute: typeof MijozlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlamalar': {
      id: '/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof SozlamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tovarlar': {
      id: '/tovarlar'
      path: '/tovarlar'
      fullPath: '/tovarlar'
      preLoaderRoute: typeof TovarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umumiy': {
      id: '/umumiy'
      path: '/umumiy'
      fullPath: '/umumiy'
      preLoaderRoute: typeof UmumiyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-code': {
      id: '/verify-code'
      path: '/verify-code'
      fullPath: '/verify-code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoshqaruvRoute: BoshqaruvRoute,
  KassaRoute: KassaRoute,
  LoginRoute: LoginRoute,
  MijozlarRoute: MijozlarRoute,
  RegisterRoute: RegisterRoute,
  SozlamalarRoute: SozlamalarRoute,
  TovarlarRoute: TovarlarRoute,
  UmumiyRoute: UmumiyRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
